### ISSUE TITLE
Honkai Star Rail Voice Lines Missing

### ISSUE THREAD

**Issue by SimplyViper** [pipeeeeees/waze-voicepack-links#11]
Hi, first of all, thank you for making/keeping these voice packs. I've downloaded the Honkai Star Rail voice pack and it seems to be missing the roundabout line and Hazrad line. I know originally when the voice pack was first released by Waze it was missing the same lines but after a couple of weeks of using the app with the official Honkai Star Rail lines from Waze, they had updated the pack and added a roundabout and hazard line. So instead of having a default voice for the roundabout it was the Honkai Star Rail voice and for hazards instead of using the red light camera line it had and actual hazard line from the VA of Honkai Star Rail. If you could look into it or update it that would be great. I wish I knew about this before Waze took the official voice pack away from me, would have recorded the new lines. Thanks again

**Comment by pipeeeeees** [comment]
Hey thanks for catching this, I also see the issues with these two lines. I will see what can be done here

**Comment by TotherKoala** [comment]
Hi, I don't mean to rush you if it's taking a while but how are you doing with finding the updated version?

**Comment by pipeeeeees** [comment]
@TotherKoala I'm having a hard time sourcing these mp3 files, also busy with school and work recently. If I can have these mp3 files sourced and sent over to me, I can have an updated link made soon. If anyone still has the Waze official honkai star rail on their rooted android device, they should be able to retrieve these files. I, unfortunately, do not.

**Comment by TotherKoala** [comment]
Alright then. Thanks for replying so fast, let me know if you're able to get the voice files but understandably school does come first 👍

**Comment by JoshuaLeninTan** [comment]
@pipeeeeees  hi, im using the star rail voice on my android 10 phone(poco f1). however, im not familiar with how to get the voice files using my pc. also im not sure if i will be able to get the files since just a while ago, i changed the voice of my other phones waze. although, my poco f1 has not been connected to the internet for a few days already. hope i can try to help with the files.

**Comment by pipeeeeees** [comment]
> @pipeeeeees  hi, im using the star rail voice on my android 10 phone(poco f1). however, im not familiar with how to get the voice files using my pc. also im not sure if i will be able to get the files since just a while ago, i changed the voice of my other phones waze. although, my poco f1 has not been connected to the internet for a few days already. hope i can try to help with the files.

Hey Joshua - awesome! To get the files off your android device, it will need to be rooted and you have to navigate to root/data/user/0/com.waze/waze/. In that directory if I recall there is a folder named `sounds` and in there you can find the mp3 files. You may need to do some digging. Using an playstore app rooted file manager should help export those files. Lmk if this is possible for you. 

As a side note, I may have a method for getting the corrected voice files myself. My biggest bottleneck for not pursuing it yet has unfortunately been my free time. I will see if I can do it right after work today. Otherwise, if you're able to export the files, lmk

**Comment by TotherKoala** [comment]
LMAO I LITERALLY CHECKED THIS POST YESTERDAY ITS FINALLY HAPPENING

**Comment by pipeeeeees** [comment]
I believe this version should be satisfactory 😃: https://waze.com/ul?acvp=04277f8e-078e-43ad-8de9-05a757c2b574
Let me know if there are any other issues. I am surprised by how much support the HSR community has behind this.

@SimplyViper @JoshuaLeninTan @TotherKoala

**Comment by SimplyViper** [comment]
This is amazing, thank you for getting this.

**Comment by JoshuaLeninTan** [comment]
hi @pipeeeeees unfortunately, my phone is not rooted. based on your latest reply, I am assuming that you have already fixed the file? thanks very much.

**Comment by TotherKoala** [comment]
Finally!! Good job man

**Comment by pipeeeeees** [comment]
Closing as the issue has been resolved
