### ISSUE TITLE
Tom Cruise Waze Voicepack

### ISSUE THREAD

**Issue by arctic-alexa** [pipeeeeees/waze-voicepack-links#17]
Thank you so much for making so many Waze voices available in one place and for creating a way to convert mp3s to a custom voice!  This is really awesome.

I used ElevenLabs to create the mp3s in Tom Cruise's voice, and I would really appreciate if you'd like to convert these into a shareable Waze link. 

I've added the mp3 files to this github repository - https://github.com/arctic-alexa/TC-Waze-Voice

I've added a star to the file names for files I couldn't find matches for in the mp3_filenames.txt or other_mp3_filenames lists.  There were also quite a few filenames listed that I don't see in my own Waze (ex. 200meters, TickerPoints, etc.).  If it would be helpful for others, I can create any additional files as needed!

Thank you!

**Comment by pipeeeeees** [comment]
Hey no problem! Here is the link let me know if you like it: https://waze.com/ul?acvp=81785741-4e08-4b3b-b260-f5e2b79c08dc

As for the names you could not find, TickerPoints is for rereouting (odd naming choice, I did not make it), 200.mp3 is a tenth of a mile, 400 a quarter, 800 half mile, 1500 is a mile. 200meters, 400meters, etc are for metric distances. If you go into your Waze settings you can change from Miles to Meters and it will change those callouts. With what you have provided me, I made the link with only miles and nothing for meters. Should you choose to want meters or offer meters, update your repo with those 5 mp3 callouts. 

These files required some compression down to 72kbps in order to be still shareable, which is pretty good. Usually 64kbps is what I'd consider good.

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=81785741-4e08-4b3b-b260-f5e2b79c08dc

**Comment by arctic-alexa** [comment]
Wow, thank you so much David!!

For a more complete voicepack, I've added meter/kilometer mp3s to the repository -https://github.com/arctic-alexa/TC-Waze-Voice

**Comment by pipeeeeees** [comment]
My conversion process automatically makes mp3 files louder by 3.5x. It does not seem to be too quiet in my opinion, but I've gone ahead and set it to 12.0x louder for you here: https://waze.com/ul?acvp=334d98ba-fcff-4551-ad70-f392bcf4302b

Should be plenty loud now and can be attenuated to your liking via the Waze settings. Let me know if this is still an issue or if you are satisfied with this!

**Comment by arctic-alexa** [comment]
Thank you!  I wonder if it's just something weird with my waze, because this 12x louder version is a lot better but still quiet compared to most of the other voices.  This one doesn't have the Distances and Rerouting phrases though, could you please add these and maybe make it 20x loud?  Sorry to bother again!

**Comment by pipeeeeees** [comment]
This is now 20dB louder than the original files (when I say 12x before I meant 12dB): https://waze.com/ul?acvp=c375526a-5625-4fb8-ada7-9dcc444860ea

It's so loud that on my iPhone 15 Pro in the Waze app the audio is starting to clip and sound distorted on my  phone speakers. I believe if this is still not loud enough it may be on your end. Let me know if this is still an improvement

**Comment by arctic-alexa** [comment]
Wow that is wild, it must be a phone thing (I'm on Android) as the volume for this version matches up with other voices.  Thank you so much, I really appreciate it!
