### ISSUE TITLE
Saving the uncut voice cues

### ISSUE THREAD

**Issue by ZigZag4** [pipeeeeees/waze-voicepack-links#18]
Hi pipeeeeees,
Great idea for a project, thanks so much for doing this!
After downloading the Red Fraggle voicepack, I noticed that due to Waze’s 6 second record limit for custom voices. Some of the cues had to be cut short such as the “We finished the silly creature driving game!” one.
I understand if for whatever reason you’re not able to share the complete uncut voice cues anywhere online, but have you held onto copies of them in your own personal archive? I would sure hate to think that they’re going completely missing!
Thanks so much for your time,
I appreciate it!

-ZigZag

**Comment by pipeeeeees** [comment]
Hey ZigZag. I do not retain nor distribute Waze's mp3 files unfortunately. They may be available on the Android app still if you dive into the root file system. 

It's important to remind ourselves that Waze is acting as free file storage for us, the users, to make custom voices and they will host them for free 24/7 on their data servers. It's a nice free service we all benefit from. They are losing money on it to keep us happy. It's for that reason that I try not to do anything that will upset Waze like sharing their mp3's online. You may find others in the community that will, but I am not one unfortunately. 

My thing is really in creating packs that preserve the highest audio quality. My method to making packs is not limited by the 6 second in-app record limit, rather the aggregate file size of all voice mp3s. I can make voicelines go 10 seconds long if I want, maybe more if I wanted. In the end, though, it is this aggregate file size limit (~0.8MB) imposed by Waze that can be a limiting factor for some voice packs where the voice lines are very long or very high quality (high bitrate). 

To get under the limit, either mp3 files need to be trimmed shorter or the bitrate must be lowered. In the case of Paw Patrol, there is a heavy mix of both. It's not perfect. I could make a version that preserves all of the voice lines, but the audio quality of the pack will suffer dramatically with a much lower bitrate. I could selectively worsen some voice lines not used often like roundabout-take-the-7th-exit... but those files are usually small anyways and will not free up much space. It may also be a jarring difference in audio quality while driving, so I try to avoid it. So that is why Red and some others (like Riddler, Paw Patrol, etc) needed to have some or most of the intro lines cut short.

Hope this helps, let me know if you have any questions or ideas!

**Comment by ZigZag4** [comment]
Hi Pipeeeeees, thanks for your response!

I understand that you’re not going to distribute Waze’s mp3 files, and that there’re limits that force you to trim them to create the voicepacks. That doesn’t concern me.

What I’m wondering is if you’re holding on to the original un-trimmed files for the sake of historical preservation. Or if someone else is, just in case Waze were to do away with them completely.
You may not be able to share them or upload them anywhere, your reasoning for not doing so I completely understand and agree with. I have no immediate intention to try to obtain them, I just want to know if they’re being kept safe somewhere since they couldn’t be left unaltered for the voicepacks.
Thanks again for your time!

-ZigZag

**Comment by pipeeeeees** [comment]
Hey again - no, I am not holding onto the original untrimmed files for the sake of historical preservation. I'd imagine there are a fair few people out there who are holding onto as many as they can. I, however, am not one of them. I have too many files and not enough storage these days 😅

**Comment by ZigZag4** [comment]
Gotcha, yeah storage space can be a pain often times! 😆
