### ISSUE TITLE
Master Chief higher quality mp3s

### ISSUE THREAD

**Issue by CatalogK9** [pipeeeeees/waze-voicepack-links#28]
[eng_master_chief.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/14452118/eng_master_chief.zip)
I think these are the original files, but lately my app stopped giving prompts half the time, and everything else I've downloaded since them has been warbly or missing several voice lines, and I'm not trying to root my phone to manually replace the files with these so please help

**Comment by pipeeeeees** [comment]
I believe the english master chief is already on the repo: https://github.com/pipeeeeees/waze-voicepack-links/

The link is: https://waze.com/ul?acvp=80e1fa58-109a-4f0a-b4ad-dce65154c53d

It works well on my iOS device - try it. It's also been optimized using the python files in this repo to maximize audio quality. It's impossible to make a link with the original audio quality, so the one in the link above may be the best possible without Waze opening up the aggregate filesize limit for uploads. If you have questions, please ask!

**Comment by CatalogK9** [comment]
I’ve been using it and it’s super warbly, unfortunately.

**Comment by pipeeeeees** [comment]
I have not heard of any waze voicepack warbling before. That's not typical of mp3 files to warble, they are static files which you can download for yourself off the repo and play back on any device - they do not warble. It would be an issue with the playback if you are experiencing warbling. Maybe provide a screen recording? Have you tried with other devices? 

This issue does not appear to be an issue with the voicepack, rather an issue with Waze itself. I will close this issue, but we can continue discussion in a new discussion thread if you'd like. I would be glad to help you troubleshoot if you provide more information like what phone you are using, what OS, what version of the waze app, and a recording of your experience. Otherwise, Waze support is your best bet

**Comment by CatalogK9** [comment]
Yeah, it’s most noticeable in my car (doesn’t affect any other sound playback, just the Master Chief voice lines from the pack), and harder to hear on my other devices but there for sure. So weirdSent from my iPhoneOn Mar 2, 2024, at 13:54, David Pipes ***@***.***> wrote:﻿
I have not heard of any waze voicepack warbling before. That's not typical of mp3 files to warble, they are static files which you can download for yourself off the repo and play back on any device - they do not warble. It would be an issue with the playback if you are experiencing warbling. Maybe provide a screen recording? Have you tried with other devices?
This issue does not appear to be an issue with the voicepack, rather an issue with Waze itself. I will close this issue, but we can continue discussion in a new discussion thread if you'd like. I would be glad to help you troubleshoot if you provide more information like what phone you are using, what OS, what version of the waze app, and a recording of your experience. Otherwise, Waze support is your best bet
