### ISSUE TITLE
Viper- Titanfall 2 (AI Generated)

### ISSUE THREAD

**Issue by Not-Nathani** [pipeeeeees/waze-voicepack-links#29]
Hi, would love if you could do a voicepack with this. the three lines "tickerpoints"; "Arrive"; and "StartDrive2" are original, with the rest being done by AI. took the better part of 4 hours to get things just right, but I was also working on a BT one (that might come soon). message me on discord at @nathani if anything needs to be added!
[Viper Voicepack.zip](https://github.com/pipeeeeees/waze-voicepack-links/files/14505421/Viper.Voicepack.zip)

**Comment by pipeeeeees** [comment]
Hey! Yes a few things:
1. your filenames include an extra `.mp3` in them. I wrote a script to remove them from each file easy so that's no issue, just FYI
2. you are missing all directions for meters - this is OK, just want you to be aware
3. you are missing Fourth - Seventh, StartDrive3 - 9, and ApproachAccident. It is ok to omit these, but realize that Waze will default to one of it's set default voices for these., so you will have a default voice cut in every now and then for those callouts. On start drive, you have a 7/9 chance of playing the default voice start drive rather than one of the two starts you provided. I can just copy paste these two and rename them to take up all 9 if you want. 

For your convenience: https://github.com/pipeeeeees/waze-voicepack-links/blob/main/conversion/mp3_filenames.txt

**Comment by pipeeeeees** [comment]
This issue has become stale, please reopen when you return

**Comment by Not-Nathani** [comment]
Hi again, sorry it took so long (school got in the way) but I fully remastered the voicepack with all necessary clips.
[Viper Voicepack.zip](https://github.com/user-attachments/files/16150926/Viper.Voicepack.zip)
