### ISSUE TITLE
BT-7274- Titanfall 2 (AI Generated)

### ISSUE THREAD

**Issue by Not-Nathani** [pipeeeeees/waze-voicepack-links#52]
Finally got around to finishing my BT voicepack along with [the viper one](https://github.com/pipeeeeees/waze-voicepack-links/issues/29#issuecomment-2218788634_). Probably going to work on Scorch Prime next, but we'll see. Thanks for the help!

[BT-7274.Voicepack.zip](https://github.com/user-attachments/files/16150957/BT-7274.Voicepack.zip)

**Comment by pipeeeeees** [comment]
https://waze.com/ul?acvp=9c6426c9-daca-4fd5-ac68-a271d239c995

try this one

**Comment by Not-Nathani** [comment]
just tried it. doesn't seem like any of the "StartDrive" files are working even though I can preview them in the app

**Comment by pipeeeeees** [comment]
That may be due to a long standing bug with Waze rather than the voicepack. Particularly if you are on android (although I have come across this before in iOS) the startdrive starts off as the default voice while the rest of the other lines are the custom voicepack... Waze has been slow to fix bugs and has only seemed to have introduced more as time goes on. I'm afraid there is not much I can suggest here other than maybe clearing the app cache or changing the default voice in the cutom pack.

**Comment by Not-Nathani** [comment]
yeah it's an issue on ios too... can't seem to change the default voice to anything but silence or something completely different. I tried reinstalling the app twice to no avail. Maybe reuploading the files would fix it? idk.

**Comment by pipeeeeees** [comment]
The files are already uploaded and retreivable from the server - we can validate this by downloading directly from Waze's servers using that voicepacks uuid: https://voice-prompts-ipv6.waze.com/9c6426c9-daca-4fd5-ac68-a271d239c995.tar.gz ; try it yourself

The issue is client-side related. The Waze app is just buggy, and unfortunately has been for some time now. Your issue is reproducable on my iOS device, the starting lines are all overwritten by the default voice now it seems...
